# Generated by Django 3.2.9 on 2021-12-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleeng', models.CharField(max_length=150)),
                ('titleesp', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=600)),
                ('texteng', models.TextField()),
                ('textesp', models.TextField()),
                ('linktogit', models.CharField(max_length=150)),
            ],
        ),
    ]
