# Generated by Django 3.2.9 on 2022-01-04 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workslist',
            name='uploadimg',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
