# Generated by Django 3.2.9 on 2022-02-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpage', '0004_alter_workslist_uploadimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workslist',
            name='uploadimg',
            field=models.ImageField(blank=True, default='', max_length=150, upload_to='newpage/static/img/'),
        ),
    ]
